# Generated by Django 4.2 on 2024-08-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('accounts', '0003_rename_accounts_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_accounts', to='user.user'),
        ),
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to='user.user'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
