# Generated by Django 4.2 on 2024-08-15 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser'),
        ('accounts', '0004_alter_account_agency_alter_account_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_accounts', to='user.myuser'),
        ),
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to='user.myuser'),
        ),
    ]
