# Generated by Django 4.2 on 2024-08-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser'),
        ('accounts', '0005_alter_account_agency_alter_account_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
